### ISSUE TITLE
Support for additional languages

### ISSUE THREAD

**Issue by theflow** [depfu/depfu#38]
Please use the comments and emoji reactions to vote on what you need support for.

Right now Depfu supports:

 * Ruby (Bundler)
 * JavaScript (npm and Yarn)
 * Elixir (Hex)

**Comment by theflow** [comment]
Python

**Comment by theflow** [comment]
Go

**Comment by theflow** [comment]
Java

**Comment by theflow** [comment]
PHP

**Comment by theflow** [comment]
.NET

**Comment by rpsrosario** [comment]
Rust

**Comment by franky47** [comment]
GitHub Actions:
```yml
- uses: user/repo@{version}
- uses: user/repo@{gitsha1} # pinned versions are recommended for security
- uses: docker://image@{tag}
- uses: docker://image@sha256:{digestHash} # same goes for image pinning
```
