### ISSUE TITLE
Make project configurable from a repository file

### ISSUE THREAD

**Issue by Siilwyn** [depfu/depfu#40]
It would be great to have repo settings available on the online Depfu dashboard page as configurable values in a config file.

Would need to decide on three things:
**1) the location**
Can be one location like the root of the project or multiple (fallback) locations, for example inside the `.github` directory would be nice to avoid an extra 'root' file.

**2) the language**
Looking at other tools TOML, JS or JSON seem to be the most common. Since JSON is not forgiving on (single) quotes and trailing commas TOML seems to be a good option for Depfu. A great Netlify example [documentation page](https://docs.netlify.com/configure-builds/file-based-configuration/) about their TOML config.

**3) interaction with dashboard**
Either the repo file or the dashboard settings take precedence, the first being the most common in my experience. It would also be great to be able to export settings from the dashboard as config file.

Example config content, including a required version for future flexibility:
```toml
version = 1
[strategy]
  outofspec = true
  [strategy.dev-dependencies]
    outofspec = false
[schedule]
  openlimit = 3
```
